name: Test
on:
  push:
    paths-ignore: ['*.md', '*.toml']
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.9, 3.x]
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python }}
    - run: pip install -r requirements-dev.txt
    - run: pytest
